import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Beach Handball Fiesta — surface scale
        surface: '#00180d',
        'surface-dim': '#00180d',
        'surface-bright': '#213f31',
        'surface-container-lowest': '#001209',
        'surface-container-low': '#012114',
        'surface-container': '#052518',
        'surface-container-high': '#112f22',
        'surface-container-highest': '#1c3b2d',
        'surface-variant': '#1c3b2d',
        background: '#00180d',
        // Text
        'on-surface': '#c8ebd6',
        'on-surface-variant': '#d4c4b1',
        'on-background': '#c8ebd6',
        'inverse-surface': '#c8ebd6',
        'inverse-on-surface': '#183629',
        // Lines
        outline: '#9d8f7d',
        'outline-variant': '#504537',
        // Gold
        primary: '#f8bc5c',
        'on-primary': '#442c00',
        'primary-container': '#d9a043',
        'on-primary-container': '#573900',
        'inverse-primary': '#805600',
        'surface-tint': '#f8bc5c',
        // Emerald
        secondary: '#9dd2b6',
        'on-secondary': '#003825',
        'secondary-container': '#1c503a',
        'on-secondary-container': '#8cc0a5',
        // Tertiary gold
        tertiary: '#f7bc60',
        'on-tertiary': '#442b00',
        'tertiary-container': '#d8a047',
        'on-tertiary-container': '#573900',
        // Error
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        // Fixed roles
        'primary-fixed': '#ffddb0',
        'primary-fixed-dim': '#f8bc5c',
        'on-primary-fixed': '#281800',
        'on-primary-fixed-variant': '#614000',
        'secondary-fixed': '#b8efd1',
        'secondary-fixed-dim': '#9dd2b6',
        'on-secondary-fixed': '#002114',
        'on-secondary-fixed-variant': '#1c503a',
        'tertiary-fixed': '#ffddb0',
        'tertiary-fixed-dim': '#f7bc60',
        'on-tertiary-fixed': '#291800',
        'on-tertiary-fixed-variant': '#614000',
        // Raw component hues from the brand doc
        gold: '#d9a043',
        'gold-deep': '#c9933b',
        'gold-dark': '#b8832e',
        forest: '#0f2e21',
        'forest-raised': '#143d2b',
        'forest-active': '#184c37',
        'forest-deep': '#0a1f16',
        sand: '#f4f6f4',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-mobile': '16px',
        'stack-md': '12px',
        'stack-lg': '24px',
        'margin-desktop': '40px',
        'stack-sm': '4px',
        'container-padding': '32px',
        base: '8px',
      },
      fontFamily: {
        sans: ['var(--font-jakarta)', 'system-ui', 'sans-serif'],
        display: ['var(--font-space-grotesk)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-jetbrains)', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'display-hero': ['64px', { lineHeight: '72px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-hero-mobile': ['38px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['44px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl-mobile': ['30px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.06em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      boxShadow: {
        'glow-gold': '0 4px 20px rgba(217, 160, 67, 0.35)',
        'glow-gold-sm': '0 0 16px rgba(217, 160, 67, 0.4)',
        'elev-modal': '0 12px 32px -4px rgba(0, 0, 0, 0.45)',
      },
    },
  },
  plugins: [],
};

export default config;